import { AnimatePresence, motion, useReducedMotion } from 'motion/react';
import {
  easePremium,
  motionTransition,
  pageTransition,
  fadeIn,
  fadeUp,
  fadeDown,
  fadeLeft,
  fadeRight,
  scaleIn,
  zoomIn,
  staggerContainer,
  staggerItem,
  float,
  rotateInfinite,
  hoverTap,
} from './variants';

export {
  AnimatePresence,
  motion,
  useReducedMotion,
  easePremium,
  motionTransition,
  pageTransition,
  fadeIn,
  fadeUp,
  fadeDown,
  fadeLeft,
  fadeRight,
  scaleIn,
  zoomIn,
  staggerContainer,
  staggerItem,
  float,
  rotateInfinite,
  hoverTap,
};
